### ISSUE TITLE
ICAP configuration for Squid

### ISSUE THREAD

**Issue by dtollaku** [filetrust/mvp-icap-squid-cache-proxy#11]

**Comment by NourEddineX** [comment]
Need a working ICAP service to test configuration against

**Comment by NourEddineX** [comment]
ICAP service had to be added with IP address and not domains to squid.conf
So we should use 51.137.28.90 instead of gw-icap01.westeurope.azurecontainer.io

**Comment by NadHodeGW** [comment]
Tested successfully when the Icap endpoint is configured as: icap://51.137.28.90/gw_rebuild

Configure the browser to use the squid proxy
Verify that files are successfully processed through a protected url
Go to protected URL: https://engineering.glasswallsolutions.com/docs/products/cloud-sdk/sample-files/
Click download a sample file & save it
Go to file drop: & select the downloaded file to process
Expected result: The file is returned as: Clean
Actual result: The file is returned as: Clean

test unsuccessful when the endpoint is configured as: icap://gw-icap01.westeurope.azurecontainer.io/gw_rebuild
