### ISSUE TITLE
Squid Deployment Playbook Improvement--Add Config Parameter for virtual machine size to use 

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/mvp-icap-squid-cache-proxy#18]
The created virtual machine using the playbook is 3.5 Gb by default; we need to have a config parameter to allow configuration for a bigger size VM if required.

**Comment by NourEddineX** [comment]
c537d6981ac2f24ce446ba0ddf4bc0438e3c306a
new var introduced vm_size in config_vars.yaml

**Comment by NadHodeGW** [comment]
The config variable has been added in the config_vars.yaml 
vm_size: Standard_D1_v2
