### ISSUE TITLE
On rebuild failure for non supported files, the original document is not returned

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/mvp-icap-squid-cache-proxy#26]
To replicate:

Process a non supported file through the Icap server using the Icap client

Expected: 
The response code 204 is returned
The original file is returned

Actual:
The response code 204 is returned
The original file is not returned

**Comment by BigPeeg** [comment]
This is expected behaviour. If the 204 code is returned, this is signalling to the ICAP Client that the original content can be forwarded unchanged. Since this is the case, it does not return the original file as the client already has it.
