### ISSUE TITLE
Squid-proxy-cache deployment documentation

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/mvp-icap-squid-cache-proxy#3]

**Comment by NadHodeGW** [comment]
@NourEddineX 
1. - Create a help document for upwork resources to use
2. - Update the Ansible Read me with the instructions on cloning the repo for the filetrust/mvp-icap-squid-cache-proxy#19
3. - Update the Ansible Read me with the instructions on updating the config_vars.yaml with required resource group 
4. - Update the Ansible Read me with the instructions on updating the config_vars.yaml with generated private key

**Comment by NourEddineX** [comment]
@NadHodeGW  What topics do we need to include in `1. Create a help document for upwork resources to use` ?

**Comment by NourEddineX** [comment]
2, 3, and 4 pushed in the commit 1887a356cb63774e936741298028e44e4793541a

**Comment by NadHodeGW** [comment]
@NourEddineX , basically a FAQ that will help any new resource to install and run it, for example: allowing the public IP, what certificate to configure the browser with etc.. any details not in the readme i guess

**Comment by NourEddineX** [comment]
1e2ffa20a60d5a612817ae0b92d94e73b058878e Firefox configuration (Explicit)
