### ISSUE TITLE
ICAP component configured within Squid-Cache Proxy and protecting documents

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/mvp-icap-squid-cache-proxy#6]

**Comment by dtollaku** [comment]
@IslamHeggy here are AC for this feature:

Files downloaded from https://app.gohire.io/ (CV's generally PDF) are protected via ICAP functionality.
Files downloaded can be validated as a second rebuild operation (File Drop, Rebuild API, Rebuild SDK) should show a clean file.

**Comment by dtollaku** [comment]
As we discussed today in our standup this issue is solved, by the development work that is already done.

**Comment by dpatel7** [comment]
.doc file downloaded from gov.uk using reverse proxy is corrupted #24

**Comment by NadHodeGW** [comment]
This has been tested on https://www.gov.uk.glasswall-icap.com/

1-
Open https://www.gov.uk.glasswall-icap.com/
Use search function and search for file types: (for example: pdf)
Open each root menu & navigate down to documents to download
Click the file download link

Expected Result:
The document should be tagged with: "Glasswall Approved"
Actual: The document is tagged with: "Glasswall Approved"

2-
Open https://www.gov.uk.glasswall-icap.com/
Use search function and search for file types: (for example: pdf)
Open each root menu & navigate down to documents to download
Click the file download link and save the file
Go to the file drop site -https://glasswall-file-drop.azurewebsites.net/
Process the downloaded files through file drop

Expected Result: The file should be clean
Actual: The file is clean
